language: php
php:
  - 5.5.9

# Add encrypted env variables, used for setting up the test environment
env:
  global:
    # Encrypted env variable $GIT_LIBMGR_APP_NAME, wil be used to set up the Github client app name for tests
    - secure: "Uby0Y1an8aBDYH7L/dicM/T8ydurLCVlHFahBXUurpUshfbHfAx2+RuWPnzSwaSu46x2fxlLK2Aj8umSs4XF6Eu9rZ/wxVSuYMqqPaFPCRdqwZB/VGvWPMXr2bUXOVjAnKvGUqP4vSSs1snYCx1XlN9GOvrGJda1SFrTPJ3JypVHwh2sjkMp6YLhWltEXQYmP1tJ87zDQrOwb3u13i0UOWFm6Azj/yTbKAUVPVtdQtc54UeEFIJUBwvui7+371a36+pterKQr146akqwj7VRFxswUJzgiSk6HuhC6L6FkCX5kxwgqMxFSrsisLUYAb7ULbE5GCGsXqFkiQfIvpJHPF0gXVTwJ+4T2b/+ScjzmZeAnexHFfbcn5NpOwAasEMlx9IjF/o3aIHWO3jWeSZp/+/j39a+TT23rwTwdu1VFx/yM/5pQWZNBkD4o4ag2RtnQkrgBk+Q1dhi1b4oegB4gOxeDTVmAoUrHBs7QaGS0EOpaiFbl+x1KU6vl8LM7licVcQdD17UicWo+4ZSzpu2Cs/8a8+I9nfGoDnXqQKsoWgRu8GXbsDa2xpjJ37MJ1sh6Gv9TPVKN5/0QgAv80e+cfXFyF2r2nzTrQa/tYcYaU2aNI4PLZe8XtNwTQ54JRlA3GFrGtqM1wdTU56caMM6fkXVPEllNOCkjJEdp2212vA="
    # Encrypted env variable $GIT_LIBMGR_CLIENT_ID, wil be used to set up the Github client id for tests
    - secure: "ykqPLKHtuBspQXlw90mOWnj2ZVwqPReY7o58bqQVkbuffceL1nT6kkfx1XnZ7DrZfV1guS13VOK4j1kqsGYMD3sdFN+c1gFcXjiCmZZaN6LgtPNkn25f4FU0LA46q7YPvpKZ8f0uC0speMDyBh7hUlZKKGyYiffVuvs5foVTRUMEJlDY3UUYXjbowZPp10Fy4m8Z73ahyqOntagdSwoDHR/Wkd5gYXeJ24YL5dk8Ga6KvBd5aRmmWcyVNwQrqVqogs2RrsuNthp4foWlb+wM3hxsi6p1JnOtuRc3b4Own32HMWCtskUDMxFaTWNGIlbW4Sez1116yf1exDay3kw+httoYjUNFCjtgrICxIV8cke9NvNQRRIAUfjgmAB+hW+H4vtytkb0Vt5fi7d9fbQmrZHx0lpXBzNkNN4JPv7yvjvqhMiBC0mtS8mlDYWL7E4MjFBnhu7ZBu1tJYgxApSvooSXV0RMmPO1E8kiHl158DqBujE4gmviEY2GlyMnfH5gkfuKBPNy8lL+KexhEwE7889azTw5o2NuLb/jGPGZqCFLwnbH7LuUc+Iq5IjEgOrWpbboafk7VlbkGTmkYJzkRDNJwdsMujkC4q7EcS4DQfG2cB0MfsdH/g5pa8vG+c/EXBDeJv+J2aOVpakGsOM0escr81ID3RwsK9PAA7yjgdg="
    # Encrypted env variable $GIT_LIBMGR_CLIENT_SECRET, wil be used to set up the Github client secret for tests
    - secure: "JH+UC2I2Te0/MxxvUBRpW/ZB3ZPxVgNDm+uAq0i+xCpv1IsYyebFIbWPL1oVZNL7Hmt+IStR9THfsy4lNgv9vgYSM0r9D3i4CI0MeErqlS+78b1HIQFKVhHGM+5QIfQaLk6FaIpXD0MRCPBcpVauoD5n/5MqqwBBHQh5DV8H/DH0Z7DsNCc/sX4lcO9c7aM+YJbKl/HW4XLkaf4dY9yozNmieWEPief7Z6/1C5EbJPnVzOyUYGPoo+CBUzxTkbV2AslJLwq4tO3RSVsq8gQqIXa5GRzeSGTxgbZ90W0zij2geaDDA0EPtj74K8GlgvnTm6ipoZGijIugESg2o/rdYRKpWpIjMmR7HRgZwV4LCfettHMrT7BbSkeMngZs0ihZkS4Qo9a7p2F6vMj5U/5AIs1GTjQ6JTKb+eps8AaMMsYb6kA+0smtB7yECVq2fSI3RsdONc+zUNjuhVBCCCNxx2mcojVkPGW9UAH+/UZ3bOzSa/rk6vzrta8hXsdzhW+GV90AYgWrJMHFnKXMOU0zzWKllqX3Oc3cfB4oIVuX+f+x4HLM6qVIzlLj4x6u3ZifWxYl8mODj8ISObToo9AQNVyvtkd9fayapfG8Yf4UUrIOx+jTSP+8M3/mKAIi4hxPW5JGHtHXxDI5ri8btVO7R8bd55GCuVF7/xzGH8e+ICE="

before_script:
  # Change the default user-password pair for mysql (pre-installed on Travis CI)
  - mysql -u root -e "UPDATE user SET Password=PASSWORD('hello') WHERE User='root';FLUSH PRIVILEGES;" mysql
  - sudo service mysql restart
  # Install our app
  - scripts/travis_install.sh
  - cd /opt/codebender/eratosthenes/Symfony
  - sudo chmod -R 777 app/cache app/logs
  # Set error reporting to "ALL". Thus, we'll be notified of warnings too
  - echo 'error_reporting =  E_ALL' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

script:
  # Run the tests
  - sudo mkdir -p build/logs
  - sudo chmod -R 777 build/logs
  - ../scripts/configure_system.sh
  - ../scripts/run_tests.sh

after_script:
  # Generate coverage
  - php composer.phar install --dev
  - php bin/coveralls -v
