parameters:
#    codebender_library.example.class: Codebender\LibraryBundle\Example
    codebender_library.handler.class: Codebender\LibraryBundle\Handler\DefaultHandler
    codebender_library.apiHandler.class: Codebender\LibraryBundle\Handler\ApiHandler
    codebender_library.apiCommandHandler.class: Codebender\LibraryBundle\Handler\ApiCommandHandler

services:
#    codebender_library.example:
#        class: %codebender_library.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

    codebender_library.handler:
        class:  %codebender_library.handler.class%
        arguments:
            entityManager: "@doctrine.orm.entity_manager"
            containerInterface: "@service_container"

    codebender_library.apiHandler:
            class:  %codebender_library.apiHandler.class%
            arguments:
                entityManager: "@doctrine.orm.entity_manager"
                containerInterface: "@service_container"

    codebender_library.apiCommandHandler:
            class:  %codebender_library.apiCommandHandler.class%
            arguments:
                entityManager: "@doctrine.orm.entity_manager"
                containerInterface: "@service_container"